### ISSUE TITLE
All archives are not extracted

### ISSUE THREAD

**Issue by csteinmetz1** [felixCheungcheung/mixing_secrets_v2#1]
Hi Felix,

I found this issue when running `unrar.py`. I think this `exit()` command should not be called. It only extracts the first zip file and then exits.

https://github.com/felixCheungcheung/mixing_secrets_v2/blob/420c556b6d67b7a0fb4081197da435adf412f4ec/unrar.py#LL23C15-L23C23

**Comment by csteinmetz1** [comment]
Related to this. I also hit an issue on some potentially corrupt `.zip` files. 

```
Traceback (most recent call last):
  File "unrar.py", line 18, in <module>
    with ZipFile(file_path, 'r') as zip:
  File "/homes/cjs01/miniconda3/envs/ms21db/lib/python3.8/zipfile.py", line 1234, in __init__
    self._RealGetContents()
  File "/homes/cjs01/miniconda3/envs/ms21db/lib/python3.8/zipfile.py", line 1301, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

Maybe we want a try except block to skip these?

**Comment by felixCheungcheung** [comment]
Thank you Christian! 
Fixed in https://github.com/felixCheungcheung/mixing_secrets_v2/commit/43db084ca7b0ce0fc729f371712ea50111339b4f
